FakeAWSCredentials = [["AKIAJSIE27KKMHXI3BJQ", "5bEYu26084qjSFyclM/f2pz4gviSfoOg+mFwBH39"],["AKIAIOSFODNN7EXAMPLE" "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"]]
FakeAPIKeyCredentials = ["sk_0b9b5db6-fabc-49d0-b68f-12343dd4f808"]
FakeSSHPrivateKey = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDXnMvKwigppkAo3Csm0H4pnYT1XSPIvVlClcv4XwRT9wAAAJgCnxGxAp8R
sQAAAAtzc2gtZWQyNTUxOQAAACDXnMvKwigppkAo3Csm0H4pnYT1XSPIvVlClcv4XwRT9w
AAAECK/+6NsEv1ZEXamRUiI0xVjEdNwf4lfvCYNoVc78Ja/decy8rCKCmmQCjcKybQfimd
hPVdI8i9WUKVy/hfBFP3AAAAFGthcmxAREVTS1RPUC1OMktHT1RRAQ==
-----END OPENSSH PRIVATE KEY-----"""
print(str(FakeAWSCredentials))
print(FakeAPIKeyCredentials)
print(FakeSSHPrivateKey)
